### ISSUE TITLE
Relative URL from 'Upload Publication' then openfile.php checks for absolute

### ISSUE THREAD

**Issue by JacobDorman** [ericmann/WP-Publication-Archive#11]
The 'upload publication' functionality returns a relative url by default (hence the message about using absolute above I guess)

then openfile.php checks for absolute.

``` php
if ( strpos( $_GET['file'], (isset($_SERVER['HTTPS']) ? 'https|' : 'http|') . $_SERVER['SERVER_NAME'] ) === false )
    die();
```

**Comment by ericmann** [comment]
The PHP script checks for an absolute file for a very specific reason - to prevent your site from being used as an open proxy by someone else.  Absolute URLs are required because of the way `openfile.php` streams the file contents back to the browser, but we need to check to see if the file is _actually_ on your server before doing so.  Otherwise anyone could use your system to download content from just about anywhere.

This was a security concern raised by a few industry experts several months ago, and was patched to prevent that kind of abuse.  If you think your site is pretty safe, feel free to remove that check from your copy of `openfile.php`.  It will be replaced by a better (i.e. more secure) method in the future that _will_ allow for both absolute and relative links and will allow you to attach remote content as well as local content.
