### ISSUE TITLE
Add filter in the shortcode

### ISSUE THREAD

**Issue by LucasHantz** [ericmann/WP-Publication-Archive#3]
Can we please have the ability to set a taxonomy in the shortcode and filter the publication from it ?

Exemple:
`[wp-publication-archive tag="Test"]`
or
`[wp-publication-archive category="Amazing"]`

**Comment by LucasHantz** [comment]
My bet, you already did it for the categories. I just saw it in your code. Maybe could you extend it to all taxonomy then? And inform the population that this option option is available in your FAQ, I'm sure some people will enjoy to know it !!

**Comment by ericmann** [comment]
Yes, it is available for categories, but wasn't documented yet since it's a "beta" feature that was a special request.  To use it, just add a comma-delimited list of category slugs in the shortcode:

```
[wp-publication-archive categories="cat-1, cat-2" /]
```

I plan to add other taxonomies in the future, since the system is already using a custom taxonomy (authors) that people want to use in a filter.  It's just a matter of working out a few latent bugs before I make it "public."  For instance, if you specify a slug that doesn't exist, the shortcode currently returns _everything_ rather than filtering by what's left over.  I'm not sure if I want this to the the expected functionality or not ... but I will make a decision in the next version.

**Comment by ericmann** [comment]
Will be updated in v2.5.
